# Generated by Django 3.1.5 on 2021-01-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['profile_image']},
        ),
    ]
